export const CONCEPT_TAXONOMY = [
  { conceptId: "CHEM_ORG_GOC_001", chapter: "General Organic Chemistry", topic: "Hybridisation" },
  { conceptId: "CHEM_ORG_GOC_002", chapter: "General Organic Chemistry", topic: "Inductive Effect" },
  { conceptId: "CHEM_ORG_GOC_003", chapter: "General Organic Chemistry", topic: "Resonance" },
  { conceptId: "CHEM_ORG_GOC_004", chapter: "General Organic Chemistry", topic: "Hyperconjugation" },
  { conceptId: "CHEM_ORG_GOC_005", chapter: "General Organic Chemistry", topic: "Isomerism" },
  { conceptId: "CHEM_ORG_GOC_006", chapter: "General Organic Chemistry", topic: "IUPAC Nomenclature" },
  { conceptId: "CHEM_ORG_HC_001", chapter: "Hydrocarbons", topic: "Alkanes" },
  { conceptId: "CHEM_ORG_HC_002", chapter: "Hydrocarbons", topic: "Alkenes" },
  { conceptId: "CHEM_ORG_HC_003", chapter: "Hydrocarbons", topic: "Alkynes" },
  { conceptId: "CHEM_ORG_HC_004", chapter: "Hydrocarbons", topic: "Arenes and Aromaticity" },
  { conceptId: "CHEM_ORG_HC_005", chapter: "Hydrocarbons", topic: "Markovnikov Rule" },
  { conceptId: "CHEM_ORG_HALO_001", chapter: "Haloalkanes and Haloarenes", topic: "Classification of Haloalkanes" },
  { conceptId: "CHEM_ORG_HALO_002", chapter: "Haloalkanes and Haloarenes", topic: "SN1 Reaction" },
  { conceptId: "CHEM_ORG_HALO_003", chapter: "Haloalkanes and Haloarenes", topic: "SN2 Reaction" },
  { conceptId: "CHEM_ORG_HALO_004", chapter: "Haloalkanes and Haloarenes", topic: "Elimination Reactions" },
  { conceptId: "CHEM_ORG_HALO_005", chapter: "Haloalkanes and Haloarenes", topic: "Haloarenes" },
  { conceptId: "CHEM_ORG_APE_001", chapter: "Alcohols, Phenols and Ethers", topic: "Classification and Structure" },
  { conceptId: "CHEM_ORG_APE_002", chapter: "Alcohols, Phenols and Ethers", topic: "Acidity of Alcohols and Phenols" },
  { conceptId: "CHEM_ORG_APE_003", chapter: "Alcohols, Phenols and Ethers", topic: "Lucas Test" },
  { conceptId: "CHEM_ORG_APE_004", chapter: "Alcohols, Phenols and Ethers", topic: "Reactions of Alcohols" },
  { conceptId: "CHEM_ORG_APE_005", chapter: "Alcohols, Phenols and Ethers", topic: "Ethers" },
  { conceptId: "CHEM_ORG_AKCA_001", chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Carbonyl Chemistry" },
  { conceptId: "CHEM_ORG_AKCA_002", chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Nucleophilic Addition" },
  { conceptId: "CHEM_ORG_AKCA_003", chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Enolate Formation" },
  { conceptId: "CHEM_ORG_AKCA_004", chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Aldol Reaction" },
  { conceptId: "CHEM_ORG_AKCA_005", chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Cross Aldol Reaction" },
  { conceptId: "CHEM_ORG_AKCA_006", chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Cannizzaro Reaction" },
  { conceptId: "CHEM_ORG_AKCA_007", chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Haloform Reaction" },
  { conceptId: "CHEM_ORG_AKCA_008", chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Clemmensen and Wolf-Kishner Reduction" },
  { conceptId: "CHEM_ORG_AKCA_009", chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Carboxylic Acids" },
  { conceptId: "CHEM_ORG_AKCA_010", chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Carboxylic Acid Derivatives" },
  { conceptId: "CHEM_ORG_AM_001", chapter: "Amines", topic: "Classification of Amines" },
  { conceptId: "CHEM_ORG_AM_002", chapter: "Amines", topic: "Basicity of Amines" },
  { conceptId: "CHEM_ORG_AM_003", chapter: "Amines", topic: "Diazonium Salts" },
  { conceptId: "CHEM_ORG_AM_004", chapter: "Amines", topic: "Preparation of Amines" },
  { conceptId: "CHEM_ORG_BIO_001", chapter: "Biomolecules", topic: "Carbohydrates" },
  { conceptId: "CHEM_ORG_BIO_002", chapter: "Biomolecules", topic: "Proteins and Amino Acids" },
  { conceptId: "CHEM_ORG_BIO_003", chapter: "Biomolecules", topic: "Nucleic Acids" },
  { conceptId: "CHEM_ORG_BIO_004", chapter: "Biomolecules", topic: "Vitamins and Hormones" },
  { conceptId: "CHEM_ORG_POL_001", chapter: "Polymers", topic: "Classification of Polymers" },
  { conceptId: "CHEM_ORG_POL_002", chapter: "Polymers", topic: "Addition and Condensation Polymerisation" },
  { conceptId: "CHEM_ORG_POL_003", chapter: "Polymers", topic: "Important Commercial Polymers" },
  { conceptId: "CHEM_ORG_CEL_001", chapter: "Chemistry in Everyday Life", topic: "Drugs and Medicines" },
  { conceptId: "CHEM_ORG_CEL_002", chapter: "Chemistry in Everyday Life", topic: "Food Chemicals" },
  { conceptId: "CHEM_ORG_CEL_003", chapter: "Chemistry in Everyday Life", topic: "Cleansing Agents" },
] as const;

export type ConceptEntry = typeof CONCEPT_TAXONOMY[number];

export function conceptListForPrompt(): string {
  return CONCEPT_TAXONOMY.map((c) => `${c.conceptId} | ${c.chapter} | ${c.topic}`).join("\n");
}
